on:
  push:
    branches:
      - master
name: Deploy
jobs:
  web-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push files to Current folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: eg77.mirohost.net
          username: metrouiS
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
          local-dir: ./src/
          server-dir: panda.metroui.org.ua/
